### ISSUE TITLE
Faulty Code in dialogs.html in example/templates

### ISSUE THREAD

**Issue by TheZwieback** [Bearle/django-private-chat#1]
There is some code that Django chokes on in line 237 to 242 if I try to run the example. I think it is supposed to start a new private chat window, but for some reason it can't do the reverse URL lookup. After removing the code (basically reverting to the dialogs.html of the django_private_chat app) it works fine. 

Also thanks for this nice example.

**Comment by delneg** [comment]
Looks like recent pull request might fix the issue, can't look up into it because too busy right now.

**Comment by TheZwieback** [comment]
Yes, the example is working now out of the box. Thank you.
