### ISSUE TITLE
Rooms

### ISSUE THREAD

**Issue by eriktelepovsky** [Bearle/django-private-chat#14]
Hi. This is actually not an issue, but a question. Is it possible to implement "rooms" functionality using this app? To allow multiple users chat together.

**Comment by delneg** [comment]
Hello, 
This is a neat feature, however the chat is designed to be one-to-one, e.g. for user with admin chat or private messages.
You can find rooms feature in projects like https://github.com/ploggingdev/djangochat or https://github.com/qubird/django-chatrooms
