### ISSUE TITLE
No link to docs

### ISSUE THREAD

**Issue by rossi1** [Bearle/django-private-chat#23]
* django-private-chat version:
* Django version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
If it's too long, please use http://pastebin.com
```

**Comment by delneg** [comment]
Fixed in 3182171a0f7333fcc47b8ca9d04c675599a4c416
