### ISSUE TITLE
'Send' Button not working

### ISSUE THREAD

**Issue by vdevired** [Bearle/django-private-chat#29]
* django-private-chat version: 0.2.2
* Django version: 2.1.2
* Python version: 3.7
* Operating System: Mac OS

### Description

Just trying to run the example. But the send button does not work. I suspect it is because I did not change the settings.py server and host settings. But I do not know what to change them to.

### What I Did

python manage.py run_chat_server

**Comment by delneg** [comment]
Please share the logs, this might be related to the latest 3.7 compatibility pull request

**Comment by vdevired** [comment]
I found the error. I don't have a username field so I changed the handlers.py file accordingly. I had already changed the views.py file.
