### ISSUE TITLE
I ran Python 3.7 with an error

### ISSUE THREAD

**Issue by ghost** [Bearle/django-private-chat#43]
* django-private-chat version:
* Django version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
If it's too long, please use http://pastebin.com
```
    asyncio_ensure_future = asyncio.async           # Python < 3.5
                                        ^
SyntaxError: invalid syntax

**Comment by saemideluxe** [comment]
This is a duplicate of #41

**Comment by morenoh149** [comment]
this was fixed. Please close.

**Comment by delneg** [comment]
Check 0.3.0
