### ISSUE TITLE
Getting Javascript errors while trying to integrate django-private-chat in django project

### ISSUE THREAD

**Issue by glakshmi-nyros** [Bearle/django-private-chat#47]
* django-private-chat version:django-private-chat==0.2.2
* Django version: Django==3.0.2
* Python version:Python 3.6.9
* Operating System:ubuntu

### Description

I am trying to integrate the django-private-chat for one to one messaging in my project
I followed the documentation and installed django-private-chat and when I got to http://127.0.0.1:8000/dialogs/  I am getting a blank page with the javascript errors in my console

Traceback:
Uncaught TypeError: Cannot read property 'scrollHeight' of null
    at n (scrollMonitor.js:1)
    at new t (scrollMonitor.js:1)
    at Object.<anonymous> (scrollMonitor.js:1)
    at e (scrollMonitor.js:1)
    at scrollMonitor.js:1
    at scrollMonitor.js:1
    at scrollMonitor.js:1
    at scrollMonitor.js:1
n @ scrollMonitor.js:1
t @ scrollMonitor.js:1
(anonymous) @ scrollMonitor.js:1
e @ scrollMonitor.js:1
(anonymous) @ scrollMonitor.js:1
(anonymous) @ scrollMonitor.js:1
(anonymous) @ scrollMonitor.js:1
(anonymous) @ scrollMonitor.js:1
(index):132 connected, sending: {"type":"online","session_key":" "}
(index):134 checking online opponents with: {"type":"check-online","session_key":" ","username":" "}
(index):34 Uncaught ReferenceError: scrollMonitor is not defined
    at initScrollMonitor ((index):34)
    at WebSocket.websocket.onopen ((index):136)

**Comment by delneg** [comment]
Not related to the package itself, the js is provided just an example, you don't have to use it.
Closing as not relevant
