### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by TonyRehley** [Bearle/django-private-chat#5]
Hi,

Can you give a gudie how make django-private-chat working with SSL?

**Comment by delneg** [comment]
Well, basically it is just like other websocket applications - you have to use WSS
The package itself has 'ws://' hard-coded in django_private_chat/views.py, it will be changed for you to be able to specify protocol.

**Comment by delneg** [comment]
Commits https://github.com/Bearle/django-private-chat/commit/d4cdf856576460955e55e208f38c8343f6d7e14b - https://github.com/Bearle/django-private-chat/commit/d3468dff3dc7486f9add0109eedae195a4a122b5.
I've added CHAT_WS_SERVER_PROTOCOL  settings which you can set to 'wss' and use something like [caddy](https://caddyserver.com/docs/websocket) for serving websocket requests.

**Comment by TonyRehley** [comment]
Thanks guys. All works great. WSS in frontend was needed and nignx SSL proxy between browser. Great job!
