### ISSUE TITLE
Send Button Not working.

### ISSUE THREAD

**Issue by asis-parajuli** [Bearle/django-private-chat#52]
* django-private-chat version:
* Django version: 2.2
* Python version: 3.7.2
* Operating System: 10

Everything is displayed. But my search button is not working. I can do everything from my admin panel (Creating dialogs and creating message is working from admin panel).  But the send Button on the Front-end side is not working.

I followed the instructions and commands properly. 
From installation to serving.

**Comment by tejbad** [comment]
Did you find any solution?
i am facing same issue
