### ISSUE TITLE
Will WebSocket connection automatically reconnect 

### ISSUE THREAD

**Issue by TonyRehley** [Bearle/django-private-chat#6]
I see that after some time I can't send message and need refresh the page.
Is websocket server implementation support auto-reconnect?
I use wss with SSL nginx proxy.

**Comment by delneg** [comment]
Try using https://github.com/joewalnes/reconnecting-websocket for JS at the frontend and feel free to comment on the results

**Comment by delneg** [comment]
Closing as of no response.
