### ISSUE TITLE
django-channels Implementation

### ISSUE THREAD

**Issue by sebastian-code** [Bearle/django-private-chat#8]
The README file says than the project was made the way it is now because to avoid being _"limited to be used together with Django Channels"_, to that end the app doesn't has a dedicated backend server to manage the websocket connections (which django-channels solves using Daphne), the provided solution is mounted on async funcionalities, which makes me wonder:
- How does that scales? 
- How resilient is this infrastructure in a high load scenario compared against other solutions?
- Do you have some use cases to use as example on this?
- Is there a way to integrate this app with django-channels?

**Comment by delneg** [comment]
> How does that scales? How resilient is this infrastructure in a high load scenario compared against other solutions?

 - Unfortunately, we didn't have a chance of testing this app in such a scenario. The project that we initially wanted to use this chat for was cancelled.

> Do you have some use cases to use as example on this?

- People who are using it, look them up at djangopackages

> Is there a way to integrate this app with django-channels?

- I think it should be pretty easy to merge this code with django-channels chat implementations, for example you can look at https://github.com/ploggingdev/djangochat

**Comment by sebastian-code** [comment]
Ok. thanks a lot.
